# Utilisation de l'image de base pour l'exécution
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
# Expose le container au port 80
EXPOSE 80

# Image pour la construction de l'application
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# Variables d'environnement
ENV APP_NAME matvelickov-myParfums-asp
ENV APP_PROJ ${APP_NAME}/${APP_NAME}.csproj

# Restaure les dépendances du projet
WORKDIR /src
COPY . .
RUN dotnet restore "${APP_PROJ}"

# Construire l'application
WORKDIR /src/${APP_NAME}
RUN dotnet build "${APP_NAME}.csproj" -c Release -o /app/build

# Publie l'application en mode Release
FROM build AS publish
RUN dotnet publish "${APP_NAME}.csproj" -c Release -o /app/publish

# Image finale avec l'application publiée
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "matvelickov-myParfums-asp.dll"]
